### ISSUE TITLE
Error launching GUI

### ISSUE THREAD

**Issue by GuilhermeZimeo** [multimodalspectroscopy/AIDE#1]
Dear AIDE Developers,

Firstly, I would like to thank you for sharing the code. I've just read the corresponding very interesting manuscript and am now indeed looking forward to testing AIDE with our fNIRS data collected in Brazil.

I have downloaded the developer version for Matlab and set the path as recommended in the user manual, but I am facing an issue when launching AIDE by typing "AIDE_GUI" on the command window. 

The following error has been reported to me on versions 2013b, 2016a and 2017a of Matlab:

_Error using load
Unable to read MAT-file C:\Software\AIDE\AIDE_Code\AIDE_GUI.fig. Not a binary MAT-file. Try load -ASCII to read as text.

Error in matlab.graphics.internal.figfile.FigFile/read (line 31)
hgDataVars = load(filename, '-mat', '-regexp', '^hg[M]');

Error in matlab.graphics.internal.figfile.FigFile

Error in hgload (line 50)
FF = matlab.graphics.internal.figfile.FigFile(filename);

Error in matlab.hg.internal.openfigLegacy (line 57)
    [fig, savedvisible] = hgload(filename, struct('Visible','off'));

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);

Error in gui_mainfcn (line 158)
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);

Error in AIDE_GUI (line 42)
    gui_mainfcn(gui_State, varargin{:});_

Please let me know in case you've seen this issue before. Maybe I am missing some necessary step?

Best regards,
Guilherme

**Comment by buck06191** [comment]
Hey,
We're working on a fix now. The problem was with how the binary GUI files
were stored by GitHub.
We'll let you know as soon as we've fixed the problem.

Thanks

**Comment by paola182** [comment]
Dear Guilherme,

the error was related to the registration of binary files with Git, Git corrupted .m, .fig files because they weren't properly registered. 
Please, download the updated version and let us know if you're experiencing any other problem with it.
Thanks!

Best wishes,
Paola

**Comment by GuilhermeZimeo** [comment]
Thank you very much for the prompt reply and fix! It works perfectly now.

Best,
Guilherme
